---
name: e2e
on:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.18'

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Setup golang
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-
      - name: Run local registry
        run: podman run -d -p 5000:5000 registry:2
      - name: Build test image
        uses: redhat-actions/buildah-build@d097e2e3d2a45b68a7c09040e3de33427bab66af
        id: test-image
        with:
          base-image: scratch
          image: test
          oci: true
      - name: Push test image to local registry
        uses: redhat-actions/push-to-registry@df878026e36864aa6bf9a5b7afe63637cb88ef8c
        with:
          image: ${{ steps.test-image.outputs.image }}
          registry: localhost:5000
          tls-verify: false
      - name: Run e2e tests
        run: go run mage.go E2ETest
