---
name: e2e
on:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.18'

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup golang
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-
      - name: Run local registry
        run: podman run -d -p 5000:5000 registry:2
      - name: Build test image
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76
        id: test-image
        with:
          base-image: scratch
          image: test
          oci: true
      - name: Push test image to local registry
        uses: redhat-actions/push-to-registry@9e8327fcde18a44143eda2e7dfe68eca01aeeeea
        with:
          image: ${{ steps.test-image.outputs.image }}
          registry: localhost:5000
          tls-verify: false
      - name: Run e2e tests
        run: go run mage.go E2ETest
